### ISSUE TITLE
Dark Matter Soundtrack not included as part of the artwork

### ISSUE THREAD

**Issue by Oflameo** [ZeroK-RTS/Zero-K-Artwork#10]
http://zero-k.info/Forum/Thread/24428?page=2&Search=&User=&grorder=&grdesc=False&grpage=1

TheMooseIsLoose curated an alternate soundtrack that has the same license as the current soundtrack. It is a good soundtrack. It has been up for 18 months. When will it be treated as first class artwork?

**Comment by sprunk** [comment]
prs welcome

**Comment by Oflameo** [comment]
I'll get it in today.
